
import React, { useRef } from 'react';
import { motion, useInView } from 'framer-motion';
import { AlertTriangle, Shield } from 'lucide-react';

const Disclaimer = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(containerRef, { once: true, amount: 0.2 });
  
  return (
    <div className="section-padding bg-black/30" id="disclaimer" ref={containerRef}>
      <div className="max-container">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <span className="chip bg-cyber-red/20 text-cyber-red border border-cyber-red/30 mb-4">
            LEGAL INFORMATION
          </span>
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            <span className="text-gradient">Legal</span> Disclaimer
          </h2>
        </motion.div>
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="glass-panel rounded-xl p-6 border border-white/10 max-w-4xl mx-auto relative overflow-hidden"
        >
          <div className="absolute -top-10 -right-10 opacity-5">
            <Shield size={200} />
          </div>
          
          <div className="flex items-center mb-4 text-cyber-red">
            <AlertTriangle size={20} className="mr-2" />
            <h3 className="font-bold text-lg">Important Notice</h3>
          </div>
          
          <div className="space-y-4 text-zinc-300">
            <p>
              Perfect Prompt Engine ("the Tool") is provided for educational and productivity enhancement purposes only. By using this Tool, you acknowledge and agree to the following terms:
            </p>
            
            <ol className="list-decimal pl-5 space-y-2">
              <li>
                <strong>No Guarantees:</strong> While the Tool aims to improve AI responses through prompt optimization, we make no guarantees regarding the accuracy, completeness, or quality of the responses generated by third-party AI systems using our optimized prompts.
              </li>
              
              <li>
                <strong>User Responsibility:</strong> Users are solely responsible for reviewing and verifying any information or content generated through the use of our Tool with third-party AI systems. AI Web Tools LLC accepts no responsibility for decisions made based on AI-generated content.
              </li>
              
              <li>
                <strong>Usage Limitations:</strong> The Tool must not be used for generating content that is illegal, harmful, discriminatory, or violates the rights of others. Users are responsible for complying with all applicable laws and regulations.
              </li>
              
              <li>
                <strong>Integration with Third-Party Services:</strong> The Tool interacts with third-party AI services that have their own terms of service and privacy policies. Users must comply with these third-party terms when using our Tool in conjunction with their services.
              </li>
              
              <li>
                <strong>Data Processing:</strong> The Tool may process user prompts to provide optimization services. We respect your privacy and adhere to our Privacy Policy regarding any data processed through our systems.
              </li>
            </ol>
            
            <p>
              This Tool is offered "as is" without warranties of any kind, either express or implied. AI Web Tools LLC disclaims all liability for any damages arising out of or in connection with your use of the Tool.
            </p>
            
            <p>
              By using Perfect Prompt Engine, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. For the complete terms of service, please visit our <a href="https://aiwebtools.ai/terms-of-services" target="_blank" rel="noopener noreferrer" className="text-cyber-blue hover:underline">Terms of Service</a>.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default Disclaimer;
